### ISSUE TITLE
Add proper repair materials for all gem items in the anvil

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/RotN-Bounty-Board#12]
Go to the vanillaAnvilRepair script and see examples, then implement for the spartan gem weapons

**Comment by EternalOne11** [comment]
I can do that. Since I am no longer busy.

**Comment by EternalOne11** [comment]
done with the anvil repair config but was told to move it to aether.zs and atop.zs

**Comment by EternalOne11** [comment]
ok done now need someone to proof read it and to test it.
https://github.com/SpGilbert/Rebirth-Of-The-Night/blob/master/scripts/atop.zs
https://github.com/SpGilbert/Rebirth-Of-The-Night/blob/master/scripts/aether.zs
my original anvil repair config
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/commit/991497a4a2391bea3cc68350049280995393db7d?diff=unified

**Comment by EternalOne11** [comment]
do you have a clue how to fix it?

**Comment by EternalOne11** [comment]
https://github.com/Rebirth-of-the-Night/Rebirth-Of-The-Night/pull/935 pull request in progress so taken.

**Comment by TheNelston** [comment]
Done, +40 points
