### ISSUE TITLE
Update the set bonus wiki page for 3.1

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/RotN-Bounty-Board#3]

**Comment by Stargen45** [comment]
can i claim this?

**Comment by TheNelston** [comment]
sure, whats your discord name? nvm got it

**Comment by Stargen45** [comment]
ok

**Comment by Stargen45** [comment]
so once i finish the overworld/pre dimension do i send what i've done and move on to the next?

**Comment by TheNelston** [comment]
send it once you've finished all of the updates

**Comment by Stargen45** [comment]
ok

**Comment by Stargen45** [comment]
ok

**Comment by Stargen45** [comment]
The wiki went down, so I'll finish off the overworld armours tomorrow probably just to let you know

**Comment by Stargen45** [comment]
i finished  the overworld section, i realised it doesn't seem to send the edited wiki, nvm

**Comment by Stargen45** [comment]
Ok finished it all https://wiki.rebirthofthenight.com/wiki/Set_Bonuses#Overworld%2FPre-Dimension

**Comment by Stargen45** [comment]
forgot some tf armour sets, will be done in a few minutes

**Comment by Stargen45** [comment]
https://wiki.rebirthofthenight.com/wiki/Set_Bonuses#Current_Version finished the tf stuff

**Comment by democat3457** [comment]
@TheNelston if this is marked as done, should the issue be closed?
