### ISSUE TITLE
Add a wiki page for plague

### ISSUE THREAD

**Issue by TheNelston** [Rebirth-of-the-Night/RotN-Bounty-Board#4]

**Comment by 444Portal** [comment]
Define tutorial

**Comment by TheNelston** [comment]
> Define tutorial

that wwas an unclear part, i mean just include any relevant resources (videos, text guides, etc.)

**Comment by 444Portal** [comment]
Hm ok, I'll see what I can do over the coming days

**Comment by 444Portal** [comment]
so i guess ill claim thjis

**Comment by 444Portal** [comment]
[Did the thing](https://wiki.rebirthofthenight.com/wiki/Plague)
